#cloud-config
autoinstall:
  version: 1
  locale: en_US
  keyboard:
    layout: ro

  # Disable SSH in the installer, or packer will fail to connect and stop the install
  early-commands:
    - systemctl stop ssh

  apt:
    preserve_sources_list: false
    primary:
      - arches: [default]
        uri: "http://archive.ubuntu.com/ubuntu"
    geoip: true

  identity:
    hostname: ${hostname}.local
    username: ${user.username}
    password: ${user.password}

  ssh:
    install-server: yes
    allow-pw: true

  packages:
    - htop
    - nano
    - tar
    - vim

  user-data:
    disable_root: true

  late-commands:
    - sed -ie 's/GRUB_TIMEOUT=.*/GRUB_TIMEOUT=1/' /target/etc/default/grub
    - sed -ie 's/^\(GRUB_CMDLINE_LINUX_DEFAULT\)=.*/\1="net.ifnames=0 modprobe.blacklist=floppy console=ttyS0,115200n8 no_timer_check edd=off"/' /target/etc/default/grub
